apiVersion: apps/v1
kind: Deployment
metadata :
     name: springapp
     labels: 
         name: springapp
         type: front-end
spec:
   replicas: 5
   selector: 
      matchLables:
         app: springapp
   template: 
       metadata:
           name: springapp
           labels:
             app: springapp
       spec:
          containers:
            - name: springapp
              image: bharathgsbk/spring-boot-image:${BUILD_NUMBER} 

     
         
